### PR TITLE
Fixes BZ#1653215 Operation ALTER USER failed

### LINKED ISSUE #78: ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
Facing this error while composing: `ERROR 1133 (28000) at line 1: Can't find any matching row in the user table`
```
mysql-container    | ---> 01:02:48     Waiting for MySQL to start ...
mysql-container    | 180524  1:02:48 [Note] /opt/rh/rh-mariadb100/root/usr/libexec/mysqld (mysqld 10.0.28-MariaDB) starting as process 29 ...
mysql-container    | 180524  1:02:48 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mysql-container    | 180524  1:02:48 [Note] InnoDB: The InnoDB memory heap is disabled
mysql-container    | 180524  1:02:48 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql-container    | 180524  1:02:48 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql-container    | 180524  1:02:48 [Note] InnoDB: Compressed tables use zlib 1.2.7
mysql-container    | 180524  1:02:48 [Note] InnoDB: Using Linux native AIO
mysql-container    | 180524  1:02:48 [Note] InnoDB: Using CPU crc32 instructions
mysql-container    | 180524  1:02:48 [Note] InnoDB: Initializing buffer pool, size = 32.0M
mysql-container    | 180524  1:02:48 [Note] InnoDB: Completed initialization of buffer pool
mysql-container    | 180524  1:02:48 [Note] InnoDB: Highest supported file format is Barracuda.
mysql-container    | 180524  1:02:48 [Note] InnoDB: 128 rollback segment(s) are active.
mysql-container    | 180524  1:02:48 [Note] InnoDB: Waiting for purge to start
mysql-container    | 180524  1:02:48 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.32-79.0 started; log sequence number 3795701817
mysql-container    | 180524  1:02:48 [Note] Plugin 'FEEDBACK' is disabled.
mysql-container    | 180524  1:02:48 [Warning] 'user' entry 'root@8678a873616c' ignored in --skip-name-resolve mode.
mysql-container    | 180524  1:02:48 [Warning] 'user' entry '@8678a873616c' ignored in --skip-name-resolve mode.
mysql-container    | 180524  1:02:48 [Warning] 'proxies_priv' entry '@% root@8678a873616c' ignored in --skip-name-resolve mode.
mysql-container    | 180524  1:02:48 [Note] /opt/rh/rh-mariadb100/root/usr/libexec/mysqld: ready for connections.
mysql-container    | Version: '10.0.28-MariaDB'  socket: '/tmp/mysql.sock'  port: 0  MariaDB Server
mysql-container    | ---> 01:02:49     MySQL started successfully
mysql-container    | => sourcing 50-passwd-change.sh ...
mysql-container    | ---> 01:02:49     Setting passwords ...
mysql-container    | ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
mysql-container exited with code 1
```
This is my `environment` config:
```
        environment:
          - MYSQL_DATABASE=my_db
          - MYSQL_USER=my_user
          - MYSQL_PASSWORD=my_user
```
I'm wondering why this script is attempting to setup the password, without making sure the user already exists: [root-common/usr/share/container-scripts/mysql/init/50-passwd-change.sh#L8](https://github.com/sclorg/mariadb-container/blob/master/root-common/usr/share/container-scripts/mysql/init/50-passwd-change.sh#L8) Maybe creating the user prior to setting password makes sense.
It worths to mention that following `environment` configuration works fine:
```
        environment:
          - MYSQL_ROOT_PASSWORD=whatever
```

### PR DESCRIPTION
**Pull request by hhorak**
When changing password for a different user, this user is not found in the database, so the container fails with:
```
ERROR 1396 (HY000) at line 1: Operation ALTER USER failed for 'newuser'@'%'
```
or
```
ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
```

The change adds a specific check that the user exists, and the behaviour change is that in case the user does not exist, the container does not fail, only a warning is printed.

This is a same PR as https://github.com/sclorg/mysql-container/pull/269 and should also close #78.

### CODE REVIEW

File: root-common/usr/share/container-scripts/mysql/init/50-passwd-change.sh [hunk 1]
```diff
@@ -4,9 +4,14 @@ password_change() {
   # Set the password for MySQL user and root everytime this container is started.
   # This allows to change the password by editing the deployment configuration.
   if [[ -v MYSQL_USER && -v MYSQL_PASSWORD ]]; then
+    local user_maches=$(echo "SELECT COUNT(*) AS found FROM mysql.user WHERE user='${MYSQL_USER}' AND Host='%' \G" | mysql $mysql_flags)
```
Comment (phracek) [inline root-common/usr/share/container-scripts/mysql/init/50-passwd-change.sh]: Any reason, Why `HOST` is needed? I guess, we are checking only `user`

File: test/run [hunk 2]
```diff
@@ -137,6 +138,34 @@ function run_change_password_test() {
...
+  test_connection testpassnewuser1 user foo
+  docker stop $(ct_get_cid testpassnewuser1) >/dev/null
+
+  # Create second container with changed password
+  create_container "testpassnewuser2" -e MYSQL_USER=user2 -e MYSQL_PASSWORD=bar \
+    -e MYSQL_DATABASE=db -v ${tmpdir}:/var/lib/mysql/data:Z
+  test_connection testpassnewuser2 user foo
+
+  # See whether there is an error message in the log
+  if ! docker logs $(ct_get_cid testpassnewuser2) | grep 'User .*user2.* does not exist in database' ; then
```
Comment (phracek) [inline test/run]: Why not to check 'User user2 does not exist in database` directly? I guess, wildcards are not needed.

File: root-common/usr/share/container-scripts/mysql/init/50-passwd-change.sh (hunk 1 above)
Comment (hhorak) [reply root-common/usr/share/container-scripts/mysql/init/50-passwd-change.sh]: Why host is important: we change the password for `mysql@%`, where `%` is `host`. So, even if there would be e.g. `mysql@192.168.0.0`, it does not help us, because the user would not be found either.

File: test/run (hunk 2 above)
Comment (hhorak) [reply test/run]: That's true, will fix it.

Comment (hhorak) [reply test/run]: Fixed.

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
Error for `rhel7` is caused by missing directory `sources`:

```bash
Warning: Permanently added '10.0.149.100' (ECDSA) to the list of known hosts.
bash: line 1: cd: sources: No such file or directory
Build step 'Execute a set of scripts' marked build as failure
```

**Comment by hhorak** [comment]
> ```shell
> bash: line 1: cd: sources: No such file or directory
> ```

OpenStack had some issues, so I thing it was caused by that..

**Comment by hhorak** [comment]
Thanks for the review.
